name: Coronavirus-jupyter-flex-ipywidgets-voila
channels:
- conda-forge
dependencies:
- numpy=1.18.5
- pandas=1.0.5
- geopandas=0.7.0
- plotly=4.8.1
- requests=2.23.0
- bs4=4.9.1
- ipywidgets=7.5.1
- bqplot=0.12.12
- ipyleaflet=0.13.0
- voila=0.1.21
